### PR TITLE
LPS-174305 Support specified directory to execute lang-sanitizer tool and sort printouts

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:reevaluate:1267401_7384

**Comment by Seiphon** [comment]
resent here https://github.com/Seiphon/liferay-portal/pull/61

**Pull request closed without merging**
