### PR TITLE
LPS-183124 Do not sort classpath in *.gradle

### PR DESCRIPTION
**Pull request by ling-alan-huang**
see https://github.com/liferay/liferay-portal/blob/master/modules/source-formatter.properties#L154

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
Hey @ling-alan-huang , we enfored the snakeyaml version to "2.0" [here](https://github.com/liferay/liferay-portal/blob/master/modules/source-formatter.properties#L154) , but we expecte the version is "1.32", and actually this dependency is just a compile time dependency, it will not exist in the runtime, so is there a way we can ignore the enforce-version check for this case?

**Comment by ling-alan-huang** [comment]
Add suppression for GradleDependencyArtifactsCheck in source-formatter-suppressions.xml?

**Pull request closed without merging**
