### PR TITLE
LPS-174305 Support specified directory to execute lang-sanitizer tool

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@brianwulbern Can you help check the test failures when test finished? If nothing related, Seiphon can send the PR to Brian directly.

**Comment by ling-alan-huang** [comment]
ci:reevaluate:1387401_6131

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@ling-alan-huang, @Seiphon, oh I had a comment here, not sure where it went...

The Stable job passes, so I won't be too concerned over the relevant job.  Unless a backend test specific to this case is failing, I think we can forward this to BChan directly.

**Comment by brianwulbern** [comment]
ci:stop

**Comment by Seiphon** [comment]
sent to Brian here https://github.com/brianchandotcom/liferay-portal/pull/129724

**Pull request closed without merging**
